# Generated by Django 3.1.2 on 2020-11-02 00:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=50, unique=True, verbose_name='DNI')),
                ('first_name', models.CharField(max_length=120, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('username', models.CharField(max_length=50, verbose_name='Apodo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='customer/photos')),
                ('address', models.CharField(max_length=50, verbose_name='Dirección')),
                ('birthDay', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(max_length=50, verbose_name='Género')),
                ('favoriteGenres', models.CharField(max_length=120, verbose_name='Preferencias Literarias')),
                ('date_creation', models.DateTimeField(auto_now=True)),
                ('news', models.BooleanField(default=True)),
                ('user_administrator', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('active_user', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['dni'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Número de la Tarjeta')),
                ('nameInCard', models.CharField(max_length=150, verbose_name='Nombre en Tarjeta')),
                ('month_expiration', models.CharField(blank=True, max_length=2, null=True, verbose_name='Mes de expiración')),
                ('day_expiration', models.CharField(blank=True, max_length=2, null=True, verbose_name='Día de Expiración')),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
                'ordering': ['id'],
            },
        ),
    ]
