# Generated by Django 3.1.2 on 2020-11-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitcard',
            name='icon',
            field=models.ImageField(blank=True, default='static/images/icons/pay-visa.png', null=True, upload_to=''),
        ),
    ]
