# Generated by Django 3.1.2 on 2020-11-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favoriteGenres',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Preferencias Literarias'),
        ),
    ]
