# Generated by Django 3.1.2 on 2020-11-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_amigo_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='id_receptor',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='id_receptor'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='hora_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de envio'),
        ),
        migrations.DeleteModel(
            name='Amigo',
        ),
    ]
