# Generated by Django 3.1.2 on 2020-11-23 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_debitcard_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debitcard',
            name='icon',
        ),
    ]
