# Generated by Django 3.1.2 on 2020-12-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201130_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ['hora_fecha'], 'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
    ]
