# Generated by Django 3.1.2 on 2020-12-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201209_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='contenido',
            field=models.CharField(max_length=500, verbose_name='contenido_mensaje'),
        ),
    ]
