# Generated by Django 3.1.2 on 2020-12-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201210_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='contenido',
            field=models.CharField(max_length=100, verbose_name='contenido_mensaje'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='hora_fecha',
            field=models.CharField(max_length=50, verbose_name='hora_fecha'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='id_emisor',
            field=models.CharField(max_length=50, verbose_name='id_emisor'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='id_receptor',
            field=models.CharField(max_length=50, verbose_name='id_receptor'),
        ),
    ]
