# Generated by Django 3.1.2 on 2020-12-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201210_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='hora_fecha',
            field=models.CharField(max_length=500, verbose_name='hora_fecha'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='id_chat',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='id_chat'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='id_emisor',
            field=models.CharField(max_length=500, verbose_name='id_emisor'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='id_receptor',
            field=models.CharField(max_length=500, verbose_name='id_receptor'),
        ),
    ]
