# Generated by Django 3.1.2 on 2020-11-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201109_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiteraryGenders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Género literario',
                'verbose_name_plural': 'Géneros literarios',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='favoriteGenres',
        ),
        migrations.AddField(
            model_name='user',
            name='favoriteGenres',
            field=models.ManyToManyField(to='users.LiteraryGenders'),
        ),
    ]
