# Generated by Django 3.1.2 on 2020-11-06 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_laurita'),
    ]

    operations = [
        migrations.DeleteModel(
            name='laurita',
        ),
    ]
