# Generated by Django 3.1.2 on 2020-11-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201109_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favoriteGenres',
            field=models.ManyToManyField(to='users.LiteraryGenders', verbose_name='Preferencias literarias'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino'), ('Otro', 'Otro')], max_length=9, null=True, verbose_name='Género'),
        ),
    ]
