# Generated by Django 3.1.2 on 2020-11-19 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20, verbose_name='Lenguaje')),
            ],
            options={
                'verbose_name': 'Lenguaje',
                'verbose_name_plural': 'Lenguajes',
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=13, verbose_name='ISBN')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('pages', models.CharField(blank=True, max_length=50, null=True, verbose_name='Páginas')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio')),
                ('cover', models.ImageField(blank=True, default='static/images/default-book.png', null=True, upload_to='product/%Y/%m/%d', verbose_name='Foto de portada')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('sale', models.BooleanField(default=True, verbose_name='En venta')),
                ('condition', models.CharField(blank=True, choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado')], max_length=10, null=True, verbose_name='Condición')),
                ('editorial', models.CharField(blank=True, max_length=50, null=True, verbose_name='Editorial')),
                ('author', models.CharField(max_length=50, verbose_name='Autor')),
                ('binding', models.CharField(blank=True, max_length=15, null=True, verbose_name='Encuadernación')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoría')),
                ('stock', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad en inventario')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.language', verbose_name='Idioma')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['title'],
            },
        ),
    ]
