# Generated by Django 3.1.2 on 2020-11-02 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=150, verbose_name='ISBN')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('published_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de publicación')),
                ('pages', models.CharField(max_length=50, verbose_name='Páginas')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('sale', models.BooleanField(default=True)),
                ('condition', models.CharField(max_length=10, verbose_name='Condición')),
                ('editorial', models.CharField(max_length=50, verbose_name='Editorial')),
                ('language', models.CharField(max_length=50, verbose_name='Lenguaje')),
                ('author', models.CharField(max_length=50, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['title'],
            },
        ),
    ]
