# Generated by Django 3.1.2 on 2020-11-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=13, verbose_name='ISBN')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('pages', models.CharField(blank=True, max_length=50, null=True, verbose_name='Páginas')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('sale', models.BooleanField(default=True)),
                ('condition', models.CharField(blank=True, max_length=10, null=True, verbose_name='Condición')),
                ('editorial', models.CharField(blank=True, max_length=50, null=True, verbose_name='Editorial')),
                ('language', models.CharField(max_length=50, verbose_name='Lenguaje')),
                ('author', models.CharField(max_length=50, verbose_name='Autor')),
                ('binding', models.CharField(blank=True, max_length=15, null=True, verbose_name='Encuadernación')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['title'],
            },
        ),
    ]
