# Generated by Django 3.1.2 on 2020-11-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20201106_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='binding',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Encuadernación'),
        ),
    ]
