# Generated by Django 3.1.2 on 2020-11-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_binding'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoría'),
        ),
    ]
