# Generated by Django 3.1.2 on 2020-11-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20201116_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, default='static/images/default-book.png', null=True, upload_to='product/%Y/%m/%d'),
        ),
    ]
