# Generated by Django 3.1.2 on 2020-11-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20201116_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, default='static/images/default-book.png', null=True, upload_to='product/%Y/%m/%d', verbose_name='Foto de portada'),
        ),
    ]
